# Generated by Django 4.2.5 on 2023-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='img',
            field=models.ImageField(default='deffflt', upload_to=''),
            preserve_default=False,
        ),
    ]
